import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

// Intentionally versioned so the first real-world update prompt can be
// verified after the PWA update mechanism is installed on a device.
const PWA_RELEASE = "2026-08-09.1";

// Workbox receives only the versioned build assets generated by Vite. We do
// not install a catch-all fetch handler, so Supabase Auth, PostgREST,
// Realtime and Push requests always go to the network and are never cached.
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// A new worker waits until the user has chosen "立即更新" in the app. This is
// deliberately not skipWaiting-on-install: a reload during an offline action
// could otherwise interrupt an optimistic interaction before its outbox flush.
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

function appUrl(path) {
  return new URL(path || "./", self.registration.scope).toString();
}

self.addEventListener("push", (event) => {
  const payload = event.data?.json?.() || {};
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    const appIsVisible = windows.some((client) => {
      try {
        return new URL(client.url).origin === self.location.origin && client.visibilityState === "visible";
      } catch {
        return false;
      }
    });
    if (appIsVisible) {
      windows.forEach((client) => client.postMessage({ type: "couple-push-received", payload }));
      return;
    }
    await self.registration.showNotification(payload.title || "愛的集點卡", {
      body: payload.body || "你的伴侶有新的互動",
      icon: new URL("icon-192.png", self.registration.scope).toString(),
      badge: new URL("icon-192.png", self.registration.scope).toString(),
      tag: payload.tag || "couple-interaction",
      renotify: false,
      data: { url: payload.url || appUrl("./"), notificationId: payload.notificationId || null, pwaRelease: PWA_RELEASE },
    });
  })());
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const destination = appUrl(event.notification.data?.url || "./");
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    const existing = windows.find((client) => {
      try { return new URL(client.url).origin === new URL(destination).origin; } catch { return false; }
    });
    if (existing) {
      if ("navigate" in existing) await existing.navigate(destination);
      return existing.focus();
    }
    return self.clients.openWindow(destination);
  })());
});
